#!/bin/bash
files=(~/.config/i3/wallpapers/*)
WALLPAPER=$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")
WALLPAPER2=$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")
feh -B white --bg-fill $WALLPAPER --bg-fill $WALLPAPER2
#feh -B white --bg-max $WALLPAPER --bg-max $WALLPAPER2
